#pragma once

#include <vector>
#include <cmath>
#include <algorithm>
#include <limits>

#include "../core/types.hpp"
#include "../math/delaunay.hpp"
#include "../math/bspline.hpp"
#include "../control/pure_pursuit.hpp"
#include "../control/pid_controller.hpp"

/**
 * @brief Configuration struct for Exploration Lap tuning parameters
 */
struct ExplorationConfig {
    double max_steering_angle = 1.22;
    double target_speed = 4.5;
    double local_radius = 10.0;
    double max_edge_distance = 6.0;
    double lookahead_distance = 4.0;

    double wheelbase = 1.5;

    double kp = 1.5;
    double ki = 0.05;
    double kd = 0.1;
};

/**
 * @brief Handles the exploration lap (Lap 1) of the unknown track.
 * It takes the global map of cones generated by SLAM, fitlers it to a local filed and computes
 * a safe centerline using Delaunay Triangulation, and uses Pure Pursuit + PID to control the
 * vehicle inside the track.
 */
class ExplorationPlanner {
private:
    ExplorationConfig config_;
    DelaunayTriangulator mesher;
    PurePursuit latitude_controller;
    PIDController longitude_controller;

    /** @brief Filters the global SLAM map to only look at cones inside the local radius and in front of the car  */
    std::vector<Point> extract_local_map(const std::vector<Point> &global_cones, const VehiclePose &current_pose);

    /** @brief Connects the Delaunay midpoints into an ordered sequence using Nearest Neighbor */
    std::vector<Point> order_centerline(std::vector<Point> unordered_points, const VehiclePose &current_pose);
public:
    ExplorationPlanner(const ExplorationConfig& config = ExplorationConfig())
        : config_(config),
          latitude_controller(config.wheelbase, config.lookahead_distance),
          longitude_controller(config.kp, config.ki, config.kd) {}

    /** @brief Executes the Lap 1 pipeline and returns a control command */
    ControlCommand compute_command(const VehiclePose &current_pose, double current_speed,
                                   double dt, const std::vector<Point> &global_cones);

    /** @brief Extracts the finalized closed-loop track boundaries */
    std::vector<Edge> generate_global_gates(const std::vector<Point> &all_cones) {
        mesher.triangulate(all_cones);
        return mesher.get_track_gates(config_.max_edge_distance);
    }
};

std::vector<Point> ExplorationPlanner::extract_local_map(const std::vector<Point> &global_cones, const VehiclePose &current_pose) {
    std::vector<Point> local_points;
    double half_fov = 1.57; // 90 degrees left and right

    for (const auto &cone : global_cones) {
        double dx = cone.x - current_pose.x;
        double dy = cone.y - current_pose.y;
        double dist = std::hypot(dx, dy);

        // Check if cone is within the physical search radius
        if (dist <= config_.local_radius) {
            double angle_to_cone = std::atan2(dy, dx);
            double relative_angle = angle_to_cone - current_pose.yaw;

            // Normalize angle
            relative_angle = std::atan2(std::sin(relative_angle), std::cos(relative_angle));

            // Keep the cone if it is inside the forward FOV
            if (std::abs(relative_angle) <= half_fov) local_points.push_back(cone);
        }
    }
    return local_points;
}

std::vector<Point> ExplorationPlanner::order_centerline(std::vector<Point> unordered_points, const VehiclePose &current_pose) {
    std::vector<Point> ordered_points;
    Point current_pos{current_pose.x, current_pose.y, ConeColor::UNKNOWN};

    while (!unordered_points.empty()) {
        auto closest_it = unordered_points.begin();
        double min_dist = std::numeric_limits<double>::max();
        for (auto it = unordered_points.begin(); it != unordered_points.end(); it++) {
            double dist = std::hypot(current_pos.x - it->x, current_pos.y - it->y);
            if (dist < min_dist) {
                min_dist = dist;
                closest_it = it;
            }
        }

        // Break if the next point is far away
        if (min_dist > 6.0 && !ordered_points.empty()) break;

        current_pos = *closest_it;
        ordered_points.push_back(*closest_it);
        unordered_points.erase(closest_it);
    }
    return ordered_points;
}

ControlCommand ExplorationPlanner::compute_command(const VehiclePose &current_pose, double current_speed,
                                                   double dt, const std::vector<Point> &global_cones) {

    ControlCommand cmd = {0.0, 0.0, 0.0, {0.0, 0.0, ConeColor::UNKNOWN}, config_.lookahead_distance, {}};

    if (global_cones.empty()) return cmd;

    // Generate the local boundaries and centerline
    std::vector<Point> local_cones = extract_local_map(global_cones, current_pose);
    mesher.triangulate(local_cones);
    std::vector<Point> raw_centerline = mesher.get_centerline(config_.max_edge_distance);
    std::vector<Point> centerline = order_centerline(raw_centerline, current_pose);

    // Anchor the centerline to the car's current position for a smooth B-spline
    if (!centerline.empty()) centerline.insert(centerline.begin(), {current_pose.x, current_pose.y, ConeColor::UNKNOWN});

    // Smooth path and calculate steering
    std::vector<Point> smooth_path = BSplineGenerator::generate_spline(centerline);
    double steering_angle_rad = latitude_controller.calculate_steering(current_pose, smooth_path);

    // Normalize steering to [-1.0, 1.0]
    cmd.steering = std::max(-1.0, std::min(1.0, -steering_angle_rad/config_.max_steering_angle));

    // Dynamic speed calculation (slow down on shart turns)
    double turn_severity = std::abs(steering_angle_rad) / config_.max_steering_angle;
    double dynamic_target_speed = std::max(1.5, config_.target_speed * (1.0 - (0.5 * turn_severity)));

    // PID Throttle/Brake Control
    if (dt > 0.0) {
        double pid_update = longitude_controller.calculate(dynamic_target_speed, current_speed, dt);
        double pedal = std::max(-1.0, std::min(1.0, pid_update/config_.target_speed));

        // Split the PID output into distinct throttle/brake/neutral commands
        if (pedal > 0.05) {
            cmd.throttle = pedal;
            cmd.brake = 0.0;
        } else if (pedal < -0.25) {
            cmd.throttle = 0.0;
            cmd.brake = -pedal;
        }
    }

    cmd.lookahead_point = latitude_controller.get_last_target();

    return cmd;
}